"""
Chat API endpoints for Founder Intelligence System
"""
from fastapi import APIRouter, HTTPException, Depends
from typing import List, Dict, Any, Optional
from datetime import datetime

from ..models.conversation import QueryRequest, QueryResponse, ConversationCreate, MessageCreate
from ..config.database import conversation_repo, message_repo
from ..utils.logger import get_logger

router = APIRouter(prefix="/chat", tags=["Chat"])
logger = get_logger(__name__)


@router.post("/conversations", summary="Create New Conversation")
async def create_conversation(conversation: ConversationCreate):
    """Create a new conversation session"""
    try:
        new_conversation = await conversation_repo.create_conversation(
            user_id=conversation.user_id
        )
        
        if not new_conversation:
            raise HTTPException(
                status_code=500,
                detail="Failed to create conversation"
            )
        
        logger.info(f"Created new conversation: {new_conversation['id']}")
        
        return {
            "status": "success",
            "data": new_conversation,
            "timestamp": datetime.now().isoformat()
        }
        
    except Exception as e:
        logger.error(f"Failed to create conversation: {str(e)}")
        raise HTTPException(
            status_code=500,
            detail=f"Failed to create conversation: {str(e)}"
        )


@router.get("/conversations/{conversation_id}", summary="Get Conversation")
async def get_conversation(conversation_id: str):
    """Get conversation by ID"""
    try:
        conversation = await conversation_repo.get_conversation_by_id(conversation_id)
        
        if not conversation:
            raise HTTPException(
                status_code=404,
                detail="Conversation not found"
            )
        
        # Get messages for this conversation
        messages = await message_repo.get_messages_by_conversation(conversation_id)
        
        return {
            "status": "success",
            "data": {
                "conversation": conversation,
                "messages": messages
            },
            "timestamp": datetime.now().isoformat()
        }
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Failed to get conversation {conversation_id}: {str(e)}")
        raise HTTPException(
            status_code=500,
            detail=f"Failed to get conversation: {str(e)}"
        )


@router.post("/query", summary="Process User Query")
async def process_query(request: QueryRequest):
    """
    Process user query through the Founder Copilot (Agent 5)
    
    This endpoint:
    - Analyzes user query for intent and entities
    - Retrieves relevant information from database
    - Generates response using LLM
    - Manages conversation context
    - Provides evidence-based answers
    """
    try:
        # For now, return a mock response since Agent 5 is not fully implemented
        # In the full implementation, this would call Agent 5
        
        # Create or update conversation if provided
        conversation_id = request.conversation_id
        if not conversation_id:
            new_conv = await conversation_repo.create_conversation()
            conversation_id = new_conv['id']
        
        # Store user message
        user_message = await message_repo.create_message(
            conversation_id=conversation_id,
            message_type="user",
            content=request.query
        )
        
        # Mock response (would be generated by Agent 5)
        mock_response = {
            "response_id": f"resp_{hash(request.query) % 10000}",
            "query": request.query,
            "answer": {
                "summary": f"I understand you're asking about: {request.query[:100]}...",
                "key_points": [
                    {
                        "point": "This is a mock response",
                        "importance": "medium",
                        "confidence": 0.8
                    }
                ],
                "additional_context": "Agent 5 (Founder Copilot) is not yet fully implemented"
            },
            "evidence": {
                "sources": [],
                "confidence_breakdown": {
                    "overall_confidence": 0.5,
                    "data_quality": 0.7,
                    "analysis_confidence": 0.3
                }
            },
            "confidence": {
                "overall_confidence": 0.5,
                "data_quality": 0.7,
                "analysis_confidence": 0.3
            },
            "metadata": {
                "response_time": "1.2_seconds",
                "data_freshness": "Agent 5 not implemented",
                "processing_steps": ["query_analysis", "retrieval", "generation"],
                "model_version": "mock_v1.0"
            },
            "follow_up_suggestions": [
                {
                    "question": "Would you like me to help implement the remaining agents?",
                    "reason": "Complete the system to get full functionality"
                },
                {
                    "question": "Can I clarify any part of my response?",
                    "reason": "Get more detailed information on specific topics"
                }
            ]
        }
        
        # Store assistant message
        assistant_message = await message_repo.create_message(
            conversation_id=conversation_id,
            message_type="assistant",
            content=mock_response["answer"]["summary"],
            metadata={
                "response_id": mock_response["response_id"],
                "confidence": mock_response["confidence"]
            }
        )
        
        logger.info(f"Processed query for conversation {conversation_id}")
        
        return QueryResponse(**mock_response)
        
    except Exception as e:
        logger.error(f"Failed to process query: {str(e)}")
        raise HTTPException(
            status_code=500,
            detail=f"Failed to process query: {str(e)}"
        )


@router.get("/conversations/{conversation_id}/messages", summary="Get Conversation Messages")
async def get_conversation_messages(
    conversation_id: str,
    limit: int = 50,
    offset: int = 0
):
    """Get messages for a conversation"""
    try:
        messages = await message_repo.get_messages_by_conversation(
            conversation_id, limit=limit
        )
        
        return {
            "status": "success",
            "data": {
                "conversation_id": conversation_id,
                "messages": messages,
                "total_count": len(messages)
            },
            "timestamp": datetime.now().isoformat()
        }
        
    except Exception as e:
        logger.error(f"Failed to get messages for {conversation_id}: {str(e)}")
        raise HTTPException(
            status_code=500,
            detail=f"Failed to get messages: {str(e)}"
        )


@router.post("/conversations/{conversation_id}/messages", summary="Add Message to Conversation")
async def add_message_to_conversation(
    conversation_id: str,
    message: MessageCreate
):
    """Add a new message to conversation"""
    try:
        # Verify conversation exists
        conversation = await conversation_repo.get_conversation_by_id(conversation_id)
        if not conversation:
            raise HTTPException(
                status_code=404,
                detail="Conversation not found"
            )
        
        # Add message
        new_message = await message_repo.create_message(
            conversation_id=conversation_id,
            message_type=message.message_type,
            content=message.content,
            metadata=message.metadata
        )
        
        logger.info(f"Added message to conversation {conversation_id}")
        
        return {
            "status": "success",
            "data": new_message,
            "timestamp": datetime.now().isoformat()
        }
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Failed to add message to {conversation_id}: {str(e)}")
        raise HTTPException(
            status_code=500,
            detail=f"Failed to add message: {str(e)}"
        )


@router.get("/conversations/{conversation_id}/summary", summary="Get Conversation Summary")
async def get_conversation_summary(conversation_id: str):
    """Get summary of conversation"""
    try:
        # Get conversation and messages
        conversation = await conversation_repo.get_conversation_by_id(conversation_id)
        messages = await message_repo.get_messages_by_conversation(conversation_id)
        
        if not conversation:
            raise HTTPException(
                status_code=404,
                detail="Conversation not found"
            )
        
        # Generate summary
        user_messages = [m for m in messages if m["message_type"] == "user"]
        assistant_messages = [m for m in messages if m["message_type"] == "assistant"]
        
        summary = {
            "conversation_id": conversation_id,
            "created_at": conversation.get("created_at"),
            "updated_at": conversation.get("updated_at"),
            "message_count": len(messages),
            "user_message_count": len(user_messages),
            "assistant_message_count": len(assistant_messages),
            "duration_minutes": _calculate_conversation_duration(conversation, messages),
            "topics_discussed": _extract_topics(user_messages),
            "last_activity": messages[-1]["created_at"] if messages else None
        }
        
        return {
            "status": "success",
            "data": summary,
            "timestamp": datetime.now().isoformat()
        }
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Failed to get conversation summary {conversation_id}: {str(e)}")
        raise HTTPException(
            status_code=500,
            detail=f"Failed to get conversation summary: {str(e)}"
        )


def _calculate_conversation_duration(conversation: Dict[str, Any], messages: List[Dict[str, Any]]) -> float:
    """Calculate conversation duration in minutes"""
    if not messages:
        return 0.0
    
    start_time = conversation.get("created_at")
    end_time = messages[-1]["created_at"] if messages else start_time
    
    if start_time and end_time:
        from datetime import datetime
        start = datetime.fromisoformat(start_time.replace('Z', '+00:00'))
        end = datetime.fromisoformat(end_time.replace('Z', '+00:00'))
        duration = (end - start).total_seconds() / 60
        return round(duration, 2)
    
    return 0.0


def _extract_topics(messages: List[Dict[str, Any]]) -> List[str]:
    """Extract topics from user messages"""
    if not messages:
        return []
    
    # Simple keyword extraction from user messages
    all_text = " ".join([m["content"] for m in messages])
    
    # Common topic keywords
    topic_keywords = {
        "product features": ["feature", "functionality", "capability", "add"],
        "user problems": ["problem", "issue", "bug", "error", "difficult"],
        "competition": ["competitor", "competition", "market"],
        "pricing": ["price", "cost", "subscription", "payment"],
        "ui/ux": ["design", "interface", "usability", "navigation"]
    }
    
    topics_found = []
    text_lower = all_text.lower()
    
    for topic, keywords in topic_keywords.items():
        if any(keyword in text_lower for keyword in keywords):
            topics_found.append(topic)
    
    return topics_found[:5]  # Top 5 topics
